name: Football News Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-news-bot:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت پروژه
        uses: actions/checkout@v6

      - name: نصب Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: نصب کتابخانه‌ها
        run: pip install -r requirements.txt
        
      - name: تست هوش مصنوعی
        run: python test_ai.py

      - name: اجرای ربات
        env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: ذخیره حافظه خبرها
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cache.json
          git diff --cached --quiet || git commit -m "Update news cache"
          git push
