name: Scheduler Test

on:
  workflow_dispatch:

  schedule:
    - cron: "7,12,17,22,27,32,37,42,47,52,57 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: |
          echo "================================"
          echo "SCHEDULER WORKS"
          echo "Current UTC time:"
          date -u
          echo "================================"
